name: lrda_desktop CI

on:
  push:
    branches:
      - main # replace with the name of your default branch if different
      - 121-merging-the-search-query-of-by-location-and-by-note
  pull_request:
    branches:
      - main # replace with the name of your default branch if different
      - 108-uiux-improvements-map

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Adjust according to your project's Node.js version

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install # Replace 'npm install' with 'pnpm install'
      - name: Run tests
        run: pnpm test # or 'npm test' if you're using npm
