name: lrda_desktop CI

on:
  push:
    branches:
      - main, deliverable-2 # replace with the name of your default branch if different
  pull_request:
    branches:
      - main # replace with the name of your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # Adjust according to your project's Node.js version

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --f # or 'npm install' if you're using npm
      - name: Run tests
        run: npm test # or 'npm test' if you're using npm
